export class fichaPedido {
    constructor(
       public ColoniaEntrega: String,
       public ColoniaRecepcion: String, 
       public DireccionEntrega: String,
       public DireccionRecepcion: String,
       public DepartamentoRecibe: String,
       public DepartamentoEntrega: String,
       public Especificaciones: String,
       public FechaCreacion: String, 
       public FechaHoraEntrega: String,
       public FechaHoraEntregaT: String,
       public CobroProducto: String, 
       public ConceptoPagoProducto: String,
       public FormaPagoProducto: String,
       public CobroMensajeria: String, 
       public ConceptoPagoMensajeria: String,
       public FormaPagoMensajeria: String,
       public IdPedido: Number,
       public Moneda : String,
       public MontoCobro: Number, 
       public MunicipioEntrega: String,
       public MunicipioRecepcion: String, 
       public ReferenciaRecepcion : String,
       public ReferenciaEntrega : String,
       public NombreRecibe: String,
       public Observaciones: String,
       public Socio: String, 
       public IdClienteCF: Number,
       public SolicitudCobro2:Number,
       public SolicitudCobro: String, 
       public TelefonoRecibe: String,
       public TipoProducto: String,
       public IdTipoProducto: Number,
       public ZonaEntrega: String, 
       public ZonaRecepcion: String, 
       public IdDireccionRecepcion: Number,
       public IdDepartamentoRecepcion: Number,
       public IdMunicipioRecepcion: Number,
       public IdZonaRecepcion: Number,
       public IdColoniaRecepcion: Number,
       public IdDireccionEntrega: Number,
       public IdDepartamentoEntrega: Number,
       public IdMunicipioEntrega: Number,
       public IdZonaEntrega: Number,
       public IdColoniaEntrega: Number,
       public FechaHoraEntregaC: String,
       public FechaCreacionPedido: String, 
       public IdFormaPago: Number
    ){}
};